name: VitalsGuilds
author: stevenmlittle
version: 1.0.0
main: steven.vitals2.Main
description: Guilds

commands:
 guild:
  usage: /<command>
  description: opens guild gui
 guild stats:
  usage: /<command>
  description: prints the players guild levels
 guild reload:
  usage: /<command>
  description: reload players yml
 guild help:
  usage: /<command>
  description: prints all the guild commands